### ISSUE TITLE
W = tanh(Wˆ ) * σ(Mˆ )

### ISSUE THREAD

**Issue by pushkarparanjpe** [bharathgs/NALU#1]
https://github.com/bharathgs/NALU/blob/16a4c9965ad371b48d086bfd780f0479ce311d98/nalu/core/nalu_cell.py#L22

Shouldn't W be implemented as below according to the paper ?:
W = tanh(Wˆ )  * σ(Mˆ )

**Comment by bharathgs** [comment]
@pushkarparanjpe thanks for pointing that, fixed it :slightly_smiling_face:

**Comment by pushkarparanjpe** [comment]
Sure :)
